title: RailsDoc(Î²)
description: Ruby on Rails API Documentation.
url: https://railsdoc.github.io
source: src
target_rails_version: 5.2.5
collections:
  6.0:
    specific_version: "6.0.3"
  5.2:
    specific_version: "5.2.5"
plugins:
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  card: summary
toc:
  min_level: 2
  max_level: 3
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
      toc: true
