title: RailsDoc(Î±)
description: Ruby on Rails API Documentation.
url: https://railsdoc.github.io
source: src
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
      toc: true
