title: RailsDoc(Î²)
description: Ruby on Rails API Documentation.
url: https://railsdoc.github.io
source: src
default_rails_version: 7.0.3
rails_versions:
  "6.1":
    specific_version: "6.1.6"
  "6.0":
    specific_version: "6.0.5"
  "5.2":
    specific_version: "5.2.8"
plugins:
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  card: summary
toc:
  min_level: 2
  max_level: 3
defaults:
  - scope:
      path: ""
    values:
      version: 7.0
      image: https://avatars.githubusercontent.com/u/4223
      toc: true
      root_path: '/'
  - scope:
      path: "6.1"
    values:
      version: 6.1
      root_path: '/6.1/'
  - scope:
      path: "6.0"
    values:
      version: 6.0
      root_path: '/6.0/'
  - scope:
      path: "5.2"
    values:
      version: 5.2
      root_path: '/5.2/'
