title: RailsDoc
description: Ruby on Rails API Documentation.
url: "https://railsdoc.github.io"
source: 'src'
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
twitter:
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
