services:
  app:
    # NOTE: Use Ruby 2.7 for older builds
    image: ruby:${RUBY_VERSION:-3.3}
    working_dir: /app
    volumes:
      - .:/app
    environment:
      RUBY_YJIT_ENABLE: true
      BUNDLE_AUTO_INSTALL: true
