services:
  app:
    image: ruby:3.3
    # Use Ruby 2.7 for older builds
    # image: ruby:2.7
    working_dir: /app
    volumes:
      - .:/app
    environment:
      RUBY_YJIT_ENABLE: true
      BUNDLE_AUTO_INSTALL: true
