name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true 
    - name: Jekyll Build
      run: bundle exec jekyll build
