name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: RSpec
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - name: Install Dependencies
      run: |
        sudo apt-get update
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock')}}
        restore-keys: |
          ${{ runner.os }}-bundler-
    - name: bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Run RSpec
      run: bundle exec jekyll build
