name: CI

on: [pull_request]

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Jekyll Build
      run: bundle exec jekyll build

  doc-build-latest:
    runs-on: ubuntu-latest
    name: Rails Doc Build (latest)
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: fetch Rails tags
      run: cd rails && git fetch --depth=1 origin refs/tags/v7*:refs/tags/v7*
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Doc Build
      run: rake build

  doc-build-others:
    runs-on: ubuntu-latest
    name: Rails Doc Build (older versions)
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: fetch Rails tags
      run: cd rails && git fetch --depth=1 origin refs/tags/v7*:refs/tags/v7* refs/tags/v6*:refs/tags/v6* refs/tags/v5*:refs/tags/v5*
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Doc Build
      run: rake build_multi
